name: MD-TO-HTML-ENCODER

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Installation
      working-directory: website
      run: yarn
   
    - name: Build
      working-directory: website
      run: yarn build
    
    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v2
      env:
        #ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: 'website/build/docusaurus-trial'
        if: MD-HTML-ENCODER
  echo:
    runs-on: ubuntu-latest
    
    steps:
    - run: echo -n -e "HELLO\n !\n World!" > text.txt

    - uses: pCYSl5EDgo/cat@master
  
      id: hello
      with:
        path: '/ANNMARIA1996/docusaurus-trial/tree/gh-pages/text.txt'

    - run: echo $TEXT
      env:
        TEXT: ${{ steps.hello.outputs.text }
        
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: '/docusaurus-trial'
